properties:
  acquisition_instrument_model:
    description: Manufacturers of an acquisition instrument may offer various versions
      (models) of that instrument with different features or sensitivities. Differences
      in features or sensitivities may be relevant to processing or interpretation
      of the data.
    type: string
  acquisition_instrument_vendor:
    description: An acquisition_instrument is the device that contains the signal
      detection hardware and signal processing software. Assays generate signals such
      as light of various intensities or color or signals representing molecular mass.
    type: string
  analyte_class:
    description: Analytes are the target molecules being measured with the assay.
      TODO - What are the exact strings to expect?
    type: string
  assay_category:
    description: 'Each assay is placed into one of the following 3 general categories:
      generation of images of microscopic entities, identification & quantitation
      of molecules by mass spectrometry, and determination of nucleotide sequence.
      TODO: What are the exact strings to expect?'
    type: string
  assay_type:
    description: 'The specific type of assay being executed. TODO: What are the exact
      strings to expect?'
    type: string
  data_path:
    description: Relative path to file or directory with instrument data. Downstream
      processing will depend on filename extension conventions. Required.
    type: string
  donor_id:
    description: HuBMAP Display ID of the donor of the assayed tissue.
    type: string
  execution_datetime:
    description: Start date and time of assay. YYYY-MM-DD hh:mm +/-hh:mm, where YYYY
      is the year, MM is the month with leading 0s, and DD is the day with leading
      0s, hh is the hour with leading zeros, mm are the minutes with leading zeros,
      followed by the offset from GMT.
    type: string
  is_targeted:
    description: Specifies whether or not a specific molecule(s) is/are targeted for
      detection/measurement by the assay .The CODEX analyte is protein.
    type: string
  metadata_path:
    description: Relative path to file or directory with free-form or instrument/lab
      specific metadata. Optional.
    type: string
  number_of_antibodies:
    description: Number of antibodies
    type: string
  number_of_channels:
    description: Number of fluorescent channels imaged during each cycle.
    type: string
  number_of_cycles:
    description: Number of cycles of 1. oligo application, 2. fluor application, 3.
      washes
    type: string
  operator:
    description: Name of the person responsible for executing the assay.
    type: string
  operator_email:
    description: Email address for the operator.
    type: string
  pi:
    description: Name of the principal investigator responsible for the data.
    type: string
  pi_email:
    description: Email address for the principal investigator.
    type: string
  preparation_instrument_model:
    description: The model number/name of the instrument used to prepare the sample
      for the assay
    type: string
  preparation_instrument_vendor:
    description: The manufacturer of the instrument used to prepare the sample for
      the assay.
    type: string
  protocols_io_doi:
    description: DOI for protocols.io referring to the protocol for this assay.
    type: string
  reagent_prep_protocols_io_doi:
    description: DOI for protocols.io referring to the protocol for preparing reagents
      for the assay.
    type: string
  resolution_x_unit:
    description: The unit of measurement of width of a pixel.(nm)
    type: string
  resolution_x_value:
    description: The width of a pixel. (Akoya pixel is 377nm square)
    type: string
  resolution_y_unit:
    description: The unit of measurement of height of a pixel. (nm)
    type: string
  resolution_y_value:
    description: The height of a pixel. (Akoya pixel is 377nm square)
    type: string
  resolution_z_unit:
    description: The unit of incremental distance between image slices.(um)
    type: string
  resolution_z_value:
    description: 'Optional if assay does not have multiple z-levels. Note that this
      is resolution within a given sample: z-pitch (resolution_z_value) is the increment
      distance between image slices (for Akoya, z-pitch=1.5um) ie. the microscope
      stage is moved up or down in increments of 1.5um to capture images of several
      focal planes. The best one will be used & the rest discarded. The thickness
      of the sample itself is sample metadata.'
    type: string
  section_prep_protocols_io_doi:
    description: DOI for protocols.io referring to the protocol for preparing tissue
      sections for the assay.
    type: string
  tissue_id:
    description: HuBMAP Display ID of the assayed tissue.
    type: string
